apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.name }}
  labels:
    {{- include "openops.componentLabels" (dict "root" . "component" "redis") | nindent 4 }}
spec:
  replicas: {{ .Values.redis.replicas }}
  {{- include "openops.deploymentStrategy" . | nindent 2 }}
  selector:
    matchLabels:
      {{- include "openops.componentSelectorLabels" (dict "root" . "component" "redis") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "openops.componentSelectorLabels" (dict "root" . "component" "redis") | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.securityContext.redisOverride.pod | nindent 8 }}
      {{- include "openops.priorityClassName" . | nindent 6 }}
      {{- include "openops.topologySpreadConstraints" (dict "root" . "component" "redis") | nindent 6 }}
      {{- include "openops.affinity" (dict "root" . "component" "redis") | nindent 6 }}
      containers:
      - name: {{ .Values.redis.name }}
        image: {{ .Values.redis.image }}:{{ .Values.redis.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext.redisOverride.container | nindent 10 }}
        ports:
        - containerPort: 6379
{{- with .Values.redis.resources }}
        resources:
{{ toYaml . | nindent 10 }}
{{- end }}
        volumeMounts:
        - name: redis-data
          mountPath: /data
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data-pvc