apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.engine.name }}
  labels:
    {{- include "openops.componentLabels" (dict "root" . "component" "engine") | nindent 4 }}
spec:
  replicas: {{ .Values.engine.replicas }}
  selector:
    matchLabels:
      {{- include "openops.componentSelectorLabels" (dict "root" . "component" "engine") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "openops.componentSelectorLabels" (dict "root" . "component" "engine") | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.engine.name }}
          image: "{{ .Values.image.repository }}/{{ .Values.engine.image }}:{{ .Values.global.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/bin/sh", "-c", "cp -r /var/tmp-base/. /tmp/ && node main.js" ]
          env:
            - name: NODE_OPTIONS
              value: "--no-node-snapshot"
            - name: OPS_COMPONENT
              value: engine
{{ include "openops.renderEnv" (dict "root" . "env" .Values.openopsEnv) | nindent 12 }}
{{ include "openops.renderEnv" (dict "root" . "env" .Values.engine.env) | nindent 12 }}
          ports:
            - containerPort: 3005
{{- with .Values.engine.resources }}
          resources:
{{ toYaml . | indent 12 }}
{{- end }}
