apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    {{- include "openops.componentLabels" (dict "root" . "component" "app") | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      {{- include "openops.componentSelectorLabels" (dict "root" . "component" "app") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "openops.componentSelectorLabels" (dict "root" . "component" "app") | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.image.repository }}/{{ .Values.app.image }}:{{ .Values.global.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NODE_OPTIONS
              value: "--no-node-snapshot"
            - name: OPS_COMPONENT
              value: app
{{ include "openops.renderEnv" (dict "root" . "env" .Values.openopsEnv) | nindent 12 }}
          ports:
            - containerPort: 80
{{- with .Values.app.resources }}
          resources:
{{ toYaml . | indent 12 }}
{{- end }}
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
