apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.tables.name }}
  labels:
    {{- include "openops.componentLabels" (dict "root" . "component" "tables") | nindent 4 }}
spec:
  replicas: {{ .Values.tables.replicas }}
  {{- include "openops.deploymentStrategy" . | nindent 2 }}
  selector:
    matchLabels:
      {{- include "openops.componentSelectorLabels" (dict "root" . "component" "tables") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "openops.componentSelectorLabels" (dict "root" . "component" "tables") | nindent 8 }}
{{ with include "openops.componentConfigChecksum" (dict "root" . "component" "tables") }}
      annotations:
        checksum/config: {{ . }}
{{- end }}
    spec:
      {{- include "openops.priorityClassName" . | nindent 6 }}
      {{- include "openops.topologySpreadConstraints" (dict "root" . "component" "tables") | nindent 6 }}
      {{- include "openops.affinity" (dict "root" . "component" "tables") | nindent 6 }}
      containers:
      - name: {{ .Values.tables.name }}
        image: "{{ .Values.image.repository }}/{{ .Values.tables.image }}:{{ .Values.tables.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
{{ include "openops.renderEnv" (dict "root" . "component" "tables" "env" .Values.tables.env) | nindent 10 }}
{{- with .Values.tables.resources }}
        resources:
{{ toYaml . | nindent 10 }}
{{- end }}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: tables-data
          mountPath: /baserow/data
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /baserow/backend/docker/docker-entrypoint.sh backend-healthcheck
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 8
          failureThreshold: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /baserow/backend/docker/docker-entrypoint.sh backend-healthcheck
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 8
          failureThreshold: 10
      volumes:
      - name: tables-data
        persistentVolumeClaim:
          claimName: tables-data-pvc
