apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.tables.name }}
  labels:
    app: {{ .Values.tables.name }}
spec:
  replicas: {{ .Values.tables.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.tables.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.tables.name }}
{{ with include "openops.secretChecksum" . }}
      annotations:
        checksum/secret-env: {{ . }}
{{- end }}
    spec:
      containers:
      - name: {{ .Values.tables.name }}
        image: "{{ .Values.image.repository }}/{{ .Values.tables.image }}:{{ .Values.tables.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
{{ include "openops.renderEnv" (dict "root" . "env" .Values.tables.env) | nindent 10 }}
{{- with .Values.tables.resources }}
        resources:
{{ toYaml . | indent 10 }}
{{- end }}
        volumeMounts:
        - name: tables-data
          mountPath: /baserow/data
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /baserow/backend/docker/docker-entrypoint.sh backend-healthcheck
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 8
          failureThreshold: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /baserow/backend/docker/docker-entrypoint.sh backend-healthcheck
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 8
          failureThreshold: 10
      volumes:
      - name: tables-data
        persistentVolumeClaim:
          claimName: tables-data-pvc
