apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.engine.name }}
  labels:
    app: {{ .Values.engine.name }}
spec:
  replicas: {{ .Values.engine.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.engine.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.engine.name }}
{{ with include "openops.secretChecksum" . }}
      annotations:
        checksum/secret-env: {{ . }}
{{- end }}
    spec:
      containers:
        - name: {{ .Values.engine.name }}
          image: "{{ .Values.image.repository }}/{{ .Values.engine.image }}:{{ .Values.global.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/bin/sh", "-c", "cp -r /var/tmp-base/. /tmp/ && node main.js" ]
          env:
            - name: NODE_OPTIONS
              value: "--no-node-snapshot"
            - name: OPS_COMPONENT
              value: engine
{{ include "openops.renderEnv" (dict "root" . "env" .Values.openopsEnv) | nindent 12 }}
{{ include "openops.renderEnv" (dict "root" . "env" .Values.engine.env) | nindent 12 }}
          ports:
            - containerPort: 3005
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
