apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.analytics.name }}
  labels:
    app: {{ .Values.analytics.name }}
spec:
  replicas: {{ .Values.analytics.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.analytics.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.analytics.name }}
{{ with include "openops.secretChecksum" . }}
      annotations:
        checksum/secret-env: {{ . }}
{{- end }}
    spec:
      containers:
      - name: {{ .Values.analytics.name }}
        image: "{{ .Values.image.repository }}/{{ .Values.analytics.image }}:{{ .Values.analytics.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
{{ include "openops.renderEnv" (dict "root" . "env" .Values.analytics.env) | nindent 10 }}
        ports:
        - containerPort: 8088
{{- with .Values.analytics.resources }}
        resources:
{{ toYaml . | indent 10 }}
{{- end }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8088
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 8
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8088
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 8
          failureThreshold: 10
