{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.redis.name }}
  labels:
    {{- include "openops.componentLabels" (dict "root" . "component" "redis") | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "openops.componentSelectorLabels" (dict "root" . "component" "redis") | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from app
    - from:
        - podSelector:
            matchLabels:
              {{- include "openops.componentSelectorLabels" (dict "root" . "component" "app") | nindent 14 }}
      ports:
        - protocol: TCP
          port: 6379
    # Allow traffic from engine
    - from:
        - podSelector:
            matchLabels:
              {{- include "openops.componentSelectorLabels" (dict "root" . "component" "engine") | nindent 14 }}
      ports:
        - protocol: TCP
          port: 6379
    # Allow traffic from tables
    - from:
        - podSelector:
            matchLabels:
              {{- include "openops.componentSelectorLabels" (dict "root" . "component" "tables") | nindent 14 }}
      ports:
        - protocol: TCP
          port: 6379
  egress:
    # Allow DNS
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
{{- end }}
