{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.analytics.name }}
  labels:
    {{- include "openops.componentLabels" (dict "root" . "component" "analytics") | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "openops.componentSelectorLabels" (dict "root" . "component" "analytics") | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from nginx
    - from:
        - podSelector:
            matchLabels:
              {{- include "openops.componentSelectorLabels" (dict "root" . "component" "nginx") | nindent 14 }}
      ports:
        - protocol: TCP
          port: 8088
    # Allow traffic from app
    - from:
        - podSelector:
            matchLabels:
              {{- include "openops.componentSelectorLabels" (dict "root" . "component" "app") | nindent 14 }}
      ports:
        - protocol: TCP
          port: 8088
  egress:
    # Allow DNS
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
    # Allow traffic to postgres
    - to:
        - podSelector:
            matchLabels:
              {{- include "openops.componentSelectorLabels" (dict "root" . "component" "postgres") | nindent 14 }}
      ports:
        - protocol: TCP
          port: 5432
{{- end }}
