apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  labels:
    {{- include "openops.componentLabels" (dict "root" . "component" "postgres") | nindent 4 }}
  {{- with .Values.postgres.storage.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.postgres.storage.accessModes | nindent 4 }}
  volumeMode: {{ .Values.postgres.storage.volumeMode }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
  {{- if .Values.postgres.storage.storageClass }}
  storageClassName: {{ .Values.postgres.storage.storageClass }}
  {{- end }}