apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tables-data-pvc
  labels:
    {{- include "openops.componentLabels" (dict "root" . "component" "tables") | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.tables.storage.size }}
  {{- if .Values.tables.storage.storageClass }}
  storageClassName: {{ .Values.tables.storage.storageClass }}
  {{- end }}