{{- $root := . -}}
{{- $secretSettings := default (dict) .Values.secretEnv -}}
{{- $create := true -}}
{{- if hasKey $secretSettings "create" -}}
{{- $create = $secretSettings.create -}}
{{- end -}}
{{- $existingSecret := default "" $secretSettings.existingSecret -}}
{{- if and $create (not $existingSecret) -}}
{{- $tablesSecrets := dict -}}
{{- range $k, $v := .Values.tables.env }}
{{- if eq (include "openops.isSecretKey" $k) "true" }}
{{- $_ := set $tablesSecrets $k (tpl (tpl $v $root) $root) }}
{{- end }}
{{- end }}
{{- if gt (len $tablesSecrets) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tables.name }}-secret
  labels:
    {{- include "openops.componentLabels" (dict "root" . "component" "tables") | nindent 4 }}
{{- with $secretSettings.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with $secretSettings.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
type: {{ default "Opaque" $secretSettings.type }}
{{- if hasKey $secretSettings "immutable" }}
immutable: {{ $secretSettings.immutable }}
{{- end }}
stringData:
{{- range $k, $v := $tablesSecrets }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
{{- end }}
