{{- $root := . -}}
{{- $secretSettings := default (dict) .Values.secretEnv -}}
{{- $create := true -}}
{{- if hasKey $secretSettings "create" -}}
{{- $create = $secretSettings.create -}}
{{- end -}}
{{- $existingSecret := default "" $secretSettings.existingSecret -}}
{{- if and $create (not $existingSecret) -}}
{{- $analyticsSecrets := dict -}}
{{- range $k, $v := .Values.analytics.env }}
{{- if eq (include "openops.isSecretKey" $k) "true" }}
{{- $_ := set $analyticsSecrets $k (tpl (tpl $v $root) $root) }}
{{- end }}
{{- end }}
{{- if gt (len $analyticsSecrets) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.analytics.name }}-secret
  labels:
    {{- include "openops.componentLabels" (dict "root" . "component" "analytics") | nindent 4 }}
{{- with $secretSettings.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with $secretSettings.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
type: {{ default "Opaque" $secretSettings.type }}
{{- if hasKey $secretSettings "immutable" }}
immutable: {{ $secretSettings.immutable }}
{{- end }}
stringData:
{{- range $k, $v := $analyticsSecrets }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
{{- end }}
