{{- if .Values.serviceMonitor.enabled }}
---
# ServiceMonitor for app
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.app.name }}
  labels:
    {{- include "openops.componentLabels" (dict "root" . "component" "app") | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "openops.componentSelectorLabels" (dict "root" . "component" "app") | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.app.metrics.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
---
# ServiceMonitor for engine
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.engine.name }}
  labels:
    {{- include "openops.componentLabels" (dict "root" . "component" "engine") | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "openops.componentSelectorLabels" (dict "root" . "component" "engine") | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.engine.metrics.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
---
# ServiceMonitor for tables
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.tables.name }}
  labels:
    {{- include "openops.componentLabels" (dict "root" . "component" "tables") | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "openops.componentSelectorLabels" (dict "root" . "component" "tables") | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.tables.metrics.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
---
# ServiceMonitor for analytics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.analytics.name }}
  labels:
    {{- include "openops.componentLabels" (dict "root" . "component" "analytics") | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "openops.componentSelectorLabels" (dict "root" . "component" "analytics") | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.analytics.metrics.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
