apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
  labels:
    {{- include "openops.componentLabels" (dict "root" . "component" "redis") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.redis.service.port }}
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    {{- include "openops.componentSelectorLabels" (dict "root" . "component" "redis") | nindent 4 }}