{{- if .Values.app.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openops.serviceAccountName" (dict "root" . "component" "app") }}
  labels:
    {{- include "openops.componentLabels" (dict "root" . "component" "app") | nindent 4 }}
    {{- with .Values.global.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.app.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
